name: Build Kivy APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Cloner le dépôt
        uses: actions/checkout@v2

      - name: 🐍 Installer Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: 🔧 Installer dépendances système
        run: |
          sudo apt update
          sudo apt install -y git zip unzip openjdk-17-jdk python3-pip build-essential libgl1-mesa-dev
          pip install buildozer cython

      - name: 📦 Compiler l’APK
        run: |
          buildozer android debug

      - name: 📤 Sauvegarder l’APK
        uses: actions/upload-artifact@v2
        with:
          name: Kivy-APK
          path: bin/*.apk
